-- Run this in the Supabase SQL editor. Create the first Auth user in
-- Authentication > Users, then insert that user's UUID into admin_users.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.onsite_projects (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null check (category in ('Interior Execution', 'Exterior Execution', 'Residential', 'Commercial')),
  status text not null check (status in ('Completed', 'Work In Progress', 'Ongoing')),
  location text,
  year text,
  description text not null default '',
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.onsite_project_images (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.onsite_projects(id) on delete cascade,
  image_url text not null,
  storage_path text not null unique,
  display_order integer not null default 0,
  stage text check (stage in ('Concept', 'On-Site Work', 'Completed')),
  created_at timestamptz not null default now()
);

create index if not exists onsite_projects_published_idx on public.onsite_projects (published, created_at desc);
create index if not exists onsite_project_images_project_idx on public.onsite_project_images (project_id, display_order);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid() and is_active = true
  );
$$;

alter table public.admin_users enable row level security;
alter table public.onsite_projects enable row level security;
alter table public.onsite_project_images enable row level security;

create policy "Admins can read their admin record" on public.admin_users
  for select to authenticated using (user_id = auth.uid());

create policy "Anyone can read published projects" on public.onsite_projects
  for select to anon, authenticated using (published = true or public.is_admin());
create policy "Admins can create projects" on public.onsite_projects
  for insert to authenticated with check (public.is_admin());
create policy "Admins can update projects" on public.onsite_projects
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins can delete projects" on public.onsite_projects
  for delete to authenticated using (public.is_admin());

create policy "Anyone can read images for visible projects" on public.onsite_project_images
  for select to anon, authenticated using (
    public.is_admin() or exists (
      select 1 from public.onsite_projects
      where id = project_id and published = true
    )
  );
create policy "Admins can create images" on public.onsite_project_images
  for insert to authenticated with check (public.is_admin());
create policy "Admins can update images" on public.onsite_project_images
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins can delete images" on public.onsite_project_images
  for delete to authenticated using (public.is_admin());

insert into storage.buckets (id, name, public)
values ('onsite-projects', 'onsite-projects', true)
on conflict (id) do update set public = true;

create policy "Public can view project images" on storage.objects
  for select to public using (bucket_id = 'onsite-projects');
create policy "Admins can upload project images" on storage.objects
  for insert to authenticated with check (bucket_id = 'onsite-projects' and public.is_admin());
create policy "Admins can update project images" on storage.objects
  for update to authenticated using (bucket_id = 'onsite-projects' and public.is_admin());
create policy "Admins can delete project images" on storage.objects
  for delete to authenticated using (bucket_id = 'onsite-projects' and public.is_admin());